# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bea11189b372dd9d58d4d28cf46457ff480f8247218f928e5b1072f3e872f93f9cefdb97eeffda3dde12923d7f1ae1fba3f5bc4d8bf0d1e87021e208eaf2f608

test:
  secret_key_base: 27b665a348a5901af3c9912e2629b2155a0b1171ecf751db5b741f9dca51f990a14c3cfe357af2c445dd2453c33c557b55d0a3459393d6d01bdc09ca3e3123d5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
